project:
  type: website
  output-dir: docs

website:
  title: "Grace Tompkins"
  page-footer: | 
    *Built with [Quarto](https://quarto.org)*
  navbar:
    left:
      - href: index.qmd
        text: Home
      - teaching.qmd
      - educationalleadership/index.qmd
      - research.qmd
      - blog/index.qmd
      - Requests.qmd
      
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    include-in-header: privacypolicy/google-analytics.html
    include-after-body: privacypolicy/custom-popup.html




