project:
  type: website
  output-dir: docs

website:
  google-analytics: "G-DYN8ZCNSTZ"
  title: "Grace Tompkins"
  page-footer: | 
    *Built with [Quarto](https://quarto.org)*
  navbar:
    left:
      - href: index.qmd
        text: Home
      - teaching.qmd
      - educationalleadership/index.qmd
      - research.qmd
      - blog/index.qmd
      - Requests.qmd


format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



